abbreviations = {
    "Toncoin": "TON",
    "Bitcoin": "BTC",
    "Ethereum": "ETH",
    "Ripple": "XRP",
    "Litecoin": "LTC",
    "Cardano": "ADA",
    "Polkadot": "DOT",
    "Bitcoin Cash": "BCH",
    "Chainlink": "LINK",
    "Stellar": "XLM",
    "Binance Coin": "BNB",
    "USD Coin": "USDC",
    "Wrapped Bitcoin": "WBTC",
    "Avalanche": "AVAX",
    "Solana": "SOL",
    "EOS": "EOS",
    "TRON": "TRX",
    "Monero": "XMR",
    "Tezos": "XTZ",
    "Cosmos": "ATOM",
    "Theta Network": "THETA",
    "VeChain": "VET",
    "Uniswap": "UNI",
    "Filecoin": "FIL",
    "Neo": "NEO",
    "Bitcoin SV": "BSV",
    "NEM": "XEM",
    "Kusama": "KSM",
    "Dash": "DASH",
    "Ethereum Classic": "ETC",
    "Zcash": "ZEC",
    "Wrapped UST Token": "UST",
    "Aave": "AAVE",
    "Maker": "MKR",
    "Compound": "COMP",
    "Algorand": "ALGO",
    "Crypto.com Coin": "CRO",
    "PancakeSwap": "CAKE",
    "Synthetix": "SNX",
    "Terra": "LUNA",
    "Bitcoin Gold": "BTG",
    "Elrond": "EGLD",
    "Chiliz": "CHZ",
    "Dai": "DAI",
    "Enjin Coin": "ENJ",
    "Decred": "DCR",
    "Huobi Token": "HT",
    "The Graph": "GRT",
    "SushiSwap": "SUSHI",
    "Fantom": "FTM",
    "Ontology": "ONT",
    "Hedera Hashgraph": "HBAR",
    "Curve DAO Token": "CRV",
    "Basic Attention Token": "BAT",
    "Zilliqa": "ZIL",
    "OMG Network": "OMG",
    "Celo": "CELO",
    "yearn.finance": "YFI",
    "UMA": "UMA",
    "Waves": "WAVES",
    "0x": "ZRX",
    "Ren": "REN",
    "ICON": "ICX",
    "Ankr": "ANKR",
    "Nexo": "NEXO",
    "Qtum": "QTUM",
    "SwissBorg": "CHSB",
    "Balancer": "BAL",
    "IOST": "IOST",
    "Harmony": "ONE",
    "Paxos Standard": "PAX",
    "renBTC": "RENBTC",
    "Horizen": "ZEN",
    "THORChain": "RUNE",
    "TrueUSD": "TUSD",
    "Bitcoin Diamond": "BCD",
    "Decentraland": "MANA",
    "NXM": "NXM",
    "Swipe": "SXP",
    "Mdex": "MDX",
    "DigiByte": "DGB",
    "Nervos Network": "CKB",
    "Harvest Finance": "FARM",
    "Reserve Rights": "RSR",
    "Helium": "HNT",
    "iExec RLC": "RLC",
    "Civic": "CVC",
    "Arweave": "AR",
    "Energy Web Token": "EWT",
    "Ocean Protocol": "OCEAN",
    "Golem": "GLM",
    "Status": "SNT",
    "COTI": "COTI",
    "Ampleforth": "AMPL",
    "Numeraire": "NMR",
    "Band Protocol": "BAND",
    "Injective Protocol": "INJ",
    "Bitcoin BEP2": "BTCB",
    "Akropolis": "AKRO",
    "Voyager Token": "VGX",
    "SKALE Network": "SKL",
    "Aragon": "ANT",
    "Orion Protocol": "ORN",
    "Bancor": "BNT",
    "Livepeer": "LPT",
    "Origin Protocol": "OGN",
    "Siacoin": "SC",
    "ZKSwap": "ZKS",
    "Fetch.ai": "FET",
    "Anchor Protocol": "ANC",
    "Alchemix": "ALCX",
    "SingularityNET": "AGI",
    "Persistence": "XPRT",
    "Ravencoin": "RVN",
    "Reef Finance": "REEF",
    "Pundi X": "NPXS",
    "TomoChain": "TOMO",
    "Tokamak Network": "TON"
}